### ISSUE TITLE
saferpay API error on php 7.2 Payment.Amount.Value: Token 820 is of type Float, string expected

### ISSUE THREAD

**Issue by LMSBrubaker** [extcode/cart_saferpay#4]
## Bug Report

**Current Behavior**
credit card payment fails with error

**Expected behavior/output**
saferpay site with payment should occur

**Environment**
- TYPO3 version(s): 8.7.27
- cart version: 4.8.1
- cart_saferpay version: 1.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Centos 7

**Possible Solution**
works with php7.0, fails with php 7.1,7.2

**Additional context**
the API error is as followed:
{"SpecVersion":"1.2","RequestId":"DE31O"},"Behavior":"ABORT","ErrorName":"VALIDATION_FAILED","ErrorMessage":"Request validation failed","ErrorDetail":["Payment.Amount.Value: Token 820 is of type Float, string expected"]}, curl_error , curl_errno 0HTTP-Status: 400<||||> DUMP: URL: https://test.saferpay.com/api/ <|||> JSON:

**Comment by extcode** [comment]
The error was fixed with v1.0.1.
